### ISSUE TITLE
개체 기능 연동

### ISSUE THREAD

**Issue by koh1260** [CEUKIE/ckie-front#39]
## ✨ 작업 사항

* 개체 기능을 구현한다.

## 🦄 To-do

- [X] 개체 등록
- [X] 개체 정보 조회
- [X] 개체 정보 수정
- [ ] 개체 삭제
- [ ] 개체 사진 등록
- [ ] 개체 사진 조회
