### ISSUE TITLE
사육장 기능 연동

### ISSUE THREAD

**Issue by koh1260** [CEUKIE/ckie-front#41]
## ✨ 작업 사항

* 사육장 관련 기능을 구현한다.

## 🦄 To-do

- [ ] 블루투스로 받아온 uid와 추가 정보를 통해 사육장 등록
- [ ] 사육장 등록 시 websocket 커넥션 생성
- [ ] 사육장 정보 수정
- [ ] 사육장 삭제
